language: python
python: "3.7"
sudo: required
dist: xenial
services:
  - postgresql
  - redis
  - memcached
env:
  global:
    - DJANGO_CONFIGURATION=Prod
    - SECRET_KEY=Secret
    - DATABASE_URL=postgres://postgres@localhost/travisdb
    - MEMCACHIER_SERVERS=127.0.0.1:11211
    - REDIS_URL=redis://127.0.0.1:6379/0
before_script:
  - psql -c 'create database travisdb;' -U postgres
  - python manage.py migrate --noinput
install:
  - pip install pipenv
  - pipenv install
script:
  - python manage.py check
