language: python
python: "3.7"
sudo: required
dist: xenial
install:
  - "pip install pipenv"
  - "pipenv install"
script:
  - "python manage.py migrate"
  - "python manage.py check"
env:
  - DJANGO_CONFIGURATION=Prod SECRET_KEY=Secret DATABASE_URL=postgres://postgres@localhost/travisdb
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
