# Generated by Django 2.1.2 on 2018-10-26 06:43

import django.db.models.deletion
from django.db import migrations, models

import ionia.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('island', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(default=ionia.models.get_id, editable=False, primary_key=True,
                                              serialize=False)),
                ('post', models.CharField(max_length=240)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='island.Island')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
