# Generated by Django 2.1.2 on 2018-10-26 06:43

from django.db import migrations, models

import ionia.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigIntegerField(default=ionia.models.get_id, editable=False, primary_key=True,
                                              serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
