# Generated by Django 2.1.2 on 2018-10-28 20:12

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('island', '0002_island_created_by'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='island',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=20, unique=True),
        ),
    ]
