# Generated by Django 2.1.2 on 2018-10-29 08:24

from django.db import migrations
import ionia.extras


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181028_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=ionia.extras.EmailNullField(blank=True, error_messages={'unique': 'An user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
